import type { Establishment } from '@/app/types/establishment'

export const MOCK_ESTABLISHMENTS: Establishment[] = [
  { id: '1',  name: 'Boulangerie Dupont',        address: '14 rue de la Roquette, Paris 11e', lat: 48.858, lng: 2.354, type: 'bakery',        phone: '01 43 55 XX XX', website: null,                          mapsUrl: 'https://maps.google.com', rating: 4.7, ratingCount: 214, websiteStatus: 'none', confidenceScore: 0 },
  { id: '2',  name: 'Salon de coiffure Élise',   address: '5 avenue Voltaire, Paris 11e',     lat: 48.855, lng: 2.350, type: 'hair_salon',    phone: '+33 1 40 20 30 40', website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.2, ratingCount: 34,  websiteStatus: 'none', confidenceScore: 0 },
  { id: '3',  name: 'Garage Mécanique Martin',   address: '78 rue de Charonne, Paris 11e',   lat: 48.852, lng: 2.378, type: 'car_repair',    phone: '+33 1 43 71 22 11', website: 'http://garage-martin.fr',   mapsUrl: 'https://maps.google.com', rating: 3.9, ratingCount: 17,  websiteStatus: 'outdated', confidenceScore: 15 },
  { id: '4',  name: 'Épicerie du Marché',         address: '3 rue Oberkampf, Paris 11e',      lat: 48.860, lng: 2.368, type: 'convenience',   phone: null,                website: null,                        mapsUrl: 'https://maps.google.com', rating: null, ratingCount: null, websiteStatus: 'none', confidenceScore: 0 },
  { id: '5',  name: 'Restaurant Le Petit Zinc',  address: '11 rue Saint-Benoît, Paris 6e',   lat: 48.854, lng: 2.334, type: 'restaurant',    phone: '+33 1 42 61 20 60', website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.1, ratingCount: 210, websiteStatus: 'none', confidenceScore: 0 },
  { id: '6',  name: 'Pressing Étoile',           address: '9 boulevard Voltaire, Paris 11e', lat: 48.861, lng: 2.372, type: 'laundry',       phone: null,                website: 'http://pressing-etoile.fr', mapsUrl: 'https://maps.google.com', rating: 3.7, ratingCount: 8,   websiteStatus: 'outdated', confidenceScore: 15 },
  { id: '7',  name: "Fleuriste Au Bouton d'Or",  address: '22 rue de la Roquette, Paris 11e',lat: 48.853, lng: 2.370, type: 'florist',       phone: '+33 1 48 06 30 10', website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.8, ratingCount: 56,  websiteStatus: 'none', confidenceScore: 0 },
  { id: '8',  name: 'Café de la Mairie',         address: '1 place Saint-Sulpice, Paris 6e', lat: 48.851, lng: 2.333, type: 'cafe',          phone: null,                website: null,                        mapsUrl: 'https://maps.google.com', rating: 3.8, ratingCount: 45,  websiteStatus: 'none', confidenceScore: 0 },
  { id: '9',  name: 'Pharmacie Centrale',        address: '45 rue de la République, Paris',  lat: 48.863, lng: 2.355, type: 'pharmacy',      phone: '+33 1 43 57 70 12', website: 'https://pharmacie-centrale.fr', mapsUrl: 'https://maps.google.com', rating: 4.4, ratingCount: 122, websiteStatus: 'active', confidenceScore: 75 },
  { id: '10', name: 'Serrurerie Rapide',         address: '7 rue des Taillandiers, Paris 11e',lat: 48.849, lng: 2.374, type: 'locksmith',   phone: '+33 6 12 34 56 78', website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.0, ratingCount: 29,  websiteStatus: 'none', confidenceScore: 0 },
  { id: '11', name: 'Institut Beauté Éva',       address: '34 rue Amelot, Paris 11e',        lat: 48.857, lng: 2.361, type: 'beauty_salon',  phone: null,                website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.7, ratingCount: 91,  websiteStatus: 'none', confidenceScore: 0 },
  { id: '12', name: 'Librairie du Globe',        address: '2 rue de Buci, Paris 6e',         lat: 48.852, lng: 2.337, type: 'books',         phone: null,                website: null,                        mapsUrl: 'https://maps.google.com', rating: 4.6, ratingCount: 63,  websiteStatus: 'none', confidenceScore: 0 },
]
